
development:
  adapter: postgresql
  encoding: unicode
  database: twitter_developement
  pool: 5
  username: watashi
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: twitter_test
  pool: 5
  username: watashi
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_production
  pool: 5
 